### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by huizhuansam** [clement0010/sponsorr-frontend#36]
- [x] Do not make all fields required for creating an event
- [x] Usability testing with potential users
- [x] Nav sidebar bug
